name: "godot-ci export"
on:
  push:
    branches:
      - main

env:
  GODOT_VERSION: 4.2.2
  PROJECT_PATH: godot_project
  ITCHIO_USERNAME: ${{ vars.ITCHIO_USERNAME }}
  ITCHIO_GAME: ${{ vars.ITCHIO_GAME }}
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

permissions:
  contents: write

jobs:
  export:
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.2
    strategy:
      matrix: 
        platform: 
          - { name: windows, export: "game.exe", godot_preset: "Windows Desktop" }
          - { name: linux, export: "game.x86_64", godot_preset: "Linux/X11" }
          - { name: web, export: "index.html", godot_preset: "Web" }
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          mkdir -v -p build/${{ matrix.platform.name }}
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "${{ matrix.platform.godot_preset }}" ../build/${{ matrix.platform.name }}/${{ matrix.platform.export }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}
          path: build/${{ matrix.platform.name }}
      - name: Deploy to itch.io 🚀
        if: startsWith(github.event.ref, 'refs/tags/v')
        run: |
          butler push ./build/${{ matrix.platform.name }}  $ITCHIO_USERNAME/$ITCHIO_GAME:${{ matrix.platform.name }} --userversion ${{ github.ref_name }}
      - name: Install rsync 📚
        if: matrix.platform.name == web
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        if: matrix.platform.name == web
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: build/${{ matrix.platform.name }}
